### ISSUE TITLE
Convert list to tuple

### ISSUE THREAD

**Issue by AndreyErmilov** [singulared/conflow#113]
Aioredis lib converts a list of tuples with (host, port) pairs into a set. 
So I get an [exception](https://pastebin.com/r9L4gSGm) when I use YAML
```
redis:
  sentinels:
    - ["host_1", 26379]
    - ["host_1", 26379]
    - ["host_1", 26379]
```
How can I convert list to tuple?

**Comment by singulared** [comment]
None of the supported config formats like JSON, YAML e.t.c doesn't support tuple type.
In this case, we don't have information about the correct output type for transformation.
In this issue, you should map each element in `sentinels` list into tuple manually.
